Add common dimensions across compliance queries and migrate queries to service.sp files. Closes #39
turbot/steampipe-mod-microsoft365-compliance pull request #40
Opened 2023-05-03 14:37 UTC by madhushreeray30

…ompliance queries

### Checklist
- [ ] Issue(s) linked

2023-05-09 04:16 UTC, Priyanka-Chatterjee-2000 requested changes
Please can you take a look at the suggested changes. Thanks!!

2023-05-09 04:16 UTC, Priyanka-Chatterjee-2000 commented on mod.sp
> +
```suggestion
```

2023-05-09 04:16 UTC, Priyanka-Chatterjee-2000 commented on query/directoryrole.sp
> +        tenant_id || ' has ' || count || ' global administrators.' as reason
```suggestion
      tenant_id || ' has ' || count || ' global administrators.' as reason
```

2023-05-09 04:16 UTC, Priyanka-Chatterjee-2000 commented on query/directorysetting.sp
> +      azuread_directory_setting
```suggestion
        azuread_directory_setting
```

2023-05-09 04:16 UTC, Priyanka-Chatterjee-2000 commented on query/directorysetting.sp
> +          and (name = 'BannedPasswordCheckOnPremisesMode' and value = 'Enforce')
```suggestion
      select
        tenant_id,
        id
      from
        azuread_directory_setting
      where
        display_name = 'Password Rule Settings'
        and (name = 'BannedPasswordCheckOnPremisesMode' and value = 'Enforce')
```

2023-05-09 04:16 UTC, Priyanka-Chatterjee-2000 requested changes
Please can you take a look at the suggested changes. Thanks!!

2023-05-09 06:32 UTC, Priyanka-Chatterjee-2000 commented
LGTM

2023-05-09 06:32 UTC, Priyanka-Chatterjee-2000 approved these changes

2023-05-09 11:05 UTC, khushboo9024 commented on query/group.sp
> +      azuread_group;
@Priyanka-Chatterjee-2000  `azuread_group` table support tags any reason behind not adding tag dimenstion?

2023-05-25 15:21 UTC, misraved commented
@madhushreeray30 could you please update the `docs/index.md` file with the common dimension examples?

2023-05-25 16:15 UTC, merged